enabled: true
production-mode: false
general:
  style: true
  navigation: true
  logo:
    user/themes/czyscimy/assets/images/logo/czyscimy.svg:
      name: czyscimy.svg
      type: image/svg+xml
      size: 18843
      path: user/themes/czyscimy/assets/images/logo/czyscimy.svg
